### PR TITLE
Support `net40`

### PR DESCRIPTION
**Pull request by adamchester**
This aims to enable cleanly supporting `net40` targets for #1.

The strategy here is to
1. Remove all usages of `IReadOnlyCollection<T>` and `IReadOnlyList<T>` from the public API. This should help avoid strange runtime issues when running `net40` on `net45` runtime, etc.
2. introduce`#REFLECTION_API_EVOLVED` for internal reflection API usages. Currently, they're all throwing `NotImplementedException`.
# TODO
- [x] ~~Make sure some tests exercise the failing implementation on `net40`. This is complicated by the fact that `xunit` and `dotnet-test-xunit` do not support `net40`, so we would need another way to execute the tests.~~ Added Net40Tests project + XUnit.Console in 6e7aa98
- [X] Fix failing tests on `net40`

### CODE REVIEW

**Comment by adamchester** [comment]
This now fixes #3

**Comment by nblumhardt** [comment]
@adamchester looks like you're powering through it :-) If there's anything you want a second set of eyes on just drop me an @ :-) Cheers!

**Comment by adamchester** [comment]
@nblumhardt any better idea for running net40 tests? Best I could come up with is new csproj with linked existing test files and xunit console. It seems to work, just wondering if you any better ideas?

**Comment by nblumhardt** [comment]
@adamchester this is pretty much the approach we used to take with Serilog. May be a better option but seems okay to me :-)

**Pull request merged**
