### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 304NotModified**
- Added link to F# implementation
- Added description for `$` and `@` operators

### CODE REVIEW

**Comment by 304NotModified** [comment]
@adamchester just out of curiosity, why is there a F# implementation next to the C# one? We can use both from any .NET language?

**Comment by adamchester** [comment]
Two reasons:
1. it was fun for me to write in F#
2. some do not want a nuget dependency. I was hoping to make it useful to the widest possible audience.

**Comment by adamchester** [comment]
(I suppose also that needs might be slightly different at some point - for example, F# users will expect discriminated unions and records to render slightly differently out of the box - see https://github.com/destructurama/fsharp)

**Comment by 304NotModified** [comment]
Cool! Thanks! I'm also curious to do something with F#, but haven't found a opportunity to do something with it yet.

**Pull request merged**
