### PR TITLE
fix namespaces

### PR DESCRIPTION
**Pull request by SimonCropp**
* public classes have `MessageTemplates` namespace
 * internal classes have no namespace
 * Tests have no namespace

### CODE REVIEW

**Comment by SimonCropp** [comment]
fixes https://github.com/messagetemplates/messagetemplates-csharp/issues/22

**Comment by nblumhardt** [comment]
Seems odd not to have the folder structure follow the namespace hierarchy - any reason not to do this?

Also, not sure which projects use the convention, but I haven't seen un-namespaced internal types elsewhere, keen to know the history of this one :-)

**Comment by SimonCropp** [comment]
>Seems odd not to have the folder structure follow the namespace hierarchy - any reason not to do this?

So namespaces are for discoverability from a public perspective. directory grouping is an internal concern for organising a solution structure, it usually makes sense to group common/"regularly change together" code in the same directory. So it has never made sense that the two correspond. is seems to be a cargo-cultism inherited from java. Some example where "folder structure follow the namespace hierarchy" fails.

 * for a commonly used feature you want those in the base namespace. but if there are many classes that service that feature it makes sense to group those files in a folder
 * moving a public file between two diff folders should not have to result in a breaking change to the public API
 * often, for a given feature, there may be basic and a more advanced apis. So the second could have a".Advanced" namespace so as to not pollute the base namespace. But it may make sense to have both those APIs co-located in the same dir

> I haven't seen un-namespaced internal types elsewhere

Again, namespaces are for discoverability from a public perspective. if a class is not part of the public api it serves no purpose to have them in a namespace. they just result in loosing a full tab width of horizontal real estate and having extra redundant usings in classes that consume them

http://simoncropp.com/considernotusingnamespaces

**Comment by nblumhardt** [comment]
Thanks for the link back to the post. I guess there's a fine line between cargo-cultism and convention. For a public codebase it's pretty usual to adhere to the ecosystem norms, whether or not they have a particularly compelling justification :-)

**Comment by SimonCropp** [comment]
> For a public codebase it's pretty usual to adhere to the ecosystem norms, whether or not they have a particularly compelling justification

yep heard that one from many people before :) and on the majority of those they had not kept namespaces correct when moving types between directories. so they didnt really care that much.

and if u are concerned about consistence it is trivial to create a unit test that verified the custom convention

**Comment by SimonCropp** [comment]
any more thoughts on this?

**Comment by nblumhardt** [comment]
@adamchester any thoughts? I can see the logic in the approach, but I'm also lukewarm on dealing with one codebase that uses different conventions from every other one I work with (pro/con to everything :-))

**Comment by SimonCropp** [comment]
@nblumhardt well if u cant find fault with the reasoning, you should change your other codebases ;)

**Comment by nblumhardt** [comment]
@SimonCropp :)

I agree that we need to simplify the layout of the namespaces, but changing the way we _think about_ namespaces isn't really in that scope. Can we simplify the surface area without taking on a new namespacing scheme? (And does #20 allow us to get rid of enough public types that we can try for a single, uncluttered "root" namespace?)

**Comment by SimonCropp** [comment]
no worries, no feelings hurt :)

i will close this one, since it is easy to make the namespace changes by not building on this one.

want me to submit a new PR?

**Comment by adamchester** [comment]
That would be great thanks @simoncropp

**Pull request closed without merging**
